name: Deno Release

on:
  push:
    branches:
      - master
      - edgeql-2

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout edgedb-js
        uses: actions/checkout@v2

      - name: Checkout edgedb-deno
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
          repository: edgedb/edgedb-deno
          path: packages/deno

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.24.x

      - name: Install dev deps
        run: |
          yarn

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        with:
          path: packages/driver


      - name: Write version to file
        run: |
          echo "${{ steps.package-version.outputs.current-version }}"

      # - name: Write version to file
      #   run: |
      #     echo "${{ steps.package-version.outputs.current-version }}"
      #     echo "${{ steps.package-version.outputs.current-version}}" > packages/deno/version.txt

      - name: Compile for Deno
        run: |
          yarn workspace edgedb build:deno

      - name: Push to edgedb-deno
        run: ./.github/workflows/push-edgedb-deno.sh
        shell: bash
