name: Deno Release

on:
  push:
    branches:
      - master
      - ci

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout edgedb-js
        uses: actions/checkout@v2

      - name: Checkout edgedb-deno
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
          repository: edgedb/edgedb-deno
          path: edgedb-deno

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.17.x

      - name: Install dev deps
        run: |
          yarn install

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0

      - name: Write version to file
        run: |
          echo "${{ steps.package-version.outputs.current-version }}"
          echo "${{ steps.package-version.outputs.current-version}}" > edgedb-deno/version.txt

      - name: Compile for Deno
        run: |
          yarn compileForDeno

      - name: Push to edgedb-deno
        run: ./.github/workflows/push-edgedb-deno.sh
        shell: bash
